#!/bin/bash
# railway-deploy-guide.sh - Guía paso a paso para Railway

clear
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        🚂 GUÍA DE DEPLOYMENT EN RAILWAY                       ║"
echo "║        Colombian Legal Scraper API                            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Esta guía te llevará paso a paso para deployar tu API en Railway."
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""

# Paso 1
echo "📋 PASO 1: Crear cuenta en Railway (si no la tienes)"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "  1. Abre tu navegador en: https://railway.app/"
echo "  2. Click en 'Login' o 'Start a New Project'"
echo "  3. Conecta con GitHub (recomendado) o email"
echo ""
read -p "¿Ya tienes cuenta en Railway? (presiona Enter para continuar)"

clear
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        🚂 GUÍA DE DEPLOYMENT EN RAILWAY - PASO 2              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Paso 2
echo "📦 PASO 2: Crear nuevo proyecto desde GitHub"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "  En el dashboard de Railway:"
echo ""
echo "  1. Click en 'New Project'"
echo "  2. Selecciona 'Deploy from GitHub repo'"
echo "  3. Si es la primera vez, autoriza Railway a acceder a GitHub"
echo "  4. Busca y selecciona: 'danielluque-sudo/CLKR'"
echo "  5. Branch: 'main' o 'claude/colombian-legal-scraper-2cumr'"
echo ""
echo "  Railway comenzará a analizar tu repositorio automáticamente..."
echo ""
read -p "¿Ya creaste el proyecto? (presiona Enter para continuar)"

clear
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        🚂 GUÍA DE DEPLOYMENT EN RAILWAY - PASO 3              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Paso 3
echo "🔐 PASO 3: Configurar Variables de Entorno"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "  En el dashboard de tu proyecto en Railway:"
echo ""
echo "  1. Click en la pestaña 'Variables'"
echo "  2. Click en 'RAW Editor' (más fácil)"
echo "  3. Copia y pega lo siguiente (reemplaza con tus valores):"
echo ""
echo "╭─────────────────────────────────────────────────────────────╮"
echo "│  SUPABASE_URL=your_supabase_url_here                        │"
echo "│  SUPABASE_KEY=your_supabase_key_here                        │"
echo "│  ANTHROPIC_API_KEY=your_anthropic_api_key_here             │"
echo "│  PORT=8000                                                   │"
echo "╰─────────────────────────────────────────────────────────────╯"
echo ""
echo "  💡 TIP: Abre tu archivo .env local y copia los valores reales"
echo ""

# Mostrar los valores del .env si existe
if [ -f .env ]; then
    echo "  📄 Valores desde tu archivo .env local:"
    echo ""
    echo "  ┌─────────────────────────────────────────────────────────────┐"
    grep -E "^(SUPABASE_URL|SUPABASE_KEY|ANTHROPIC_API_KEY)=" .env | sed 's/^/  │ /' | head -3
    echo "  │ PORT=8000                                                    │"
    echo "  └─────────────────────────────────────────────────────────────┘"
    echo ""
fi

read -p "¿Ya configuraste las variables? (presiona Enter para continuar)"

clear
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        🚂 GUÍA DE DEPLOYMENT EN RAILWAY - PASO 4              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Paso 4
echo "🚀 PASO 4: Deploy Automático"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "  Railway detectará automáticamente tu proyecto Python y:"
echo ""
echo "  ✅ Instalará Python 3.11"
echo "  ✅ Instalará dependencias desde requirements-deploy.txt"
echo "  ✅ Ejecutará el Procfile (uvicorn)"
echo "  ✅ Asignará un dominio público HTTPS"
echo ""
echo "  El proceso toma ~2-3 minutos."
echo ""
echo "  Puedes ver el progreso en la pestaña 'Deployments'"
echo ""
read -p "Presiona Enter cuando veas 'Active' en el deployment..."

clear
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        ✅ DEPLOYMENT COMPLETADO                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Paso 5
echo "🎉 PASO 5: Obtener tu URL y probar la API"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "  1. En Railway, ve a 'Settings' → 'Networking'"
echo "  2. Click en 'Generate Domain'"
echo "  3. Copia tu URL (será algo como):"
echo "     https://tu-proyecto.up.railway.app"
echo ""
echo "  4. Prueba tu API:"
echo ""
read -p "Ingresa la URL de tu proyecto Railway: " RAILWAY_URL

if [ ! -z "$RAILWAY_URL" ]; then
    echo ""
    echo "🧪 Probando tu API en: $RAILWAY_URL"
    echo "─────────────────────────────────────────────────────────"
    echo ""

    echo "  📍 Health Check..."
    curl -s "$RAILWAY_URL/health" | head -5
    echo ""
    echo ""

    echo "═══════════════════════════════════════════════════════════════════"
    echo ""
    echo "✅ ¡TU API ESTÁ VIVA!"
    echo ""
    echo "🔗 URLs importantes:"
    echo "   • API Home:     $RAILWAY_URL"
    echo "   • Health:       $RAILWAY_URL/health"
    echo "   • Docs:         $RAILWAY_URL/docs"
    echo "   • Railway Dashboard: https://railway.app/project/tu-proyecto"
    echo ""
    echo "🧪 Comandos de prueba:"
    echo ""
    echo "  # Health check"
    echo "  curl $RAILWAY_URL/health"
    echo ""
    echo "  # Ver documentación interactiva"
    echo "  open $RAILWAY_URL/docs"
    echo ""
    echo "  # Scrape leyes (sin límite de timeout!)"
    echo "  curl -X POST $RAILWAY_URL/scrape \\"
    echo "    -H 'Content-Type: application/json' \\"
    echo "    -d '{\"year\": 2023, \"max_laws\": 3}'"
    echo ""
    echo "  # Buscar leyes"
    echo "  curl -X POST $RAILWAY_URL/search \\"
    echo "    -H 'Content-Type: application/json' \\"
    echo "    -d '{\"query\": \"impuestos\", \"limit\": 5}'"
    echo ""
fi

echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "📚 Próximos pasos:"
echo ""
echo "  1. Prueba el endpoint /docs para ver la documentación interactiva"
echo "  2. Haz un scraping de prueba con /scrape"
echo "  3. Configura tu base de datos Supabase si aún no lo hiciste"
echo "  4. Monitorea los logs en Railway dashboard"
echo ""
echo "💡 Comandos útiles de Railway:"
echo ""
echo "  # Ver logs en tiempo real"
echo "  railway logs --follow"
echo ""
echo "  # Ver estado"
echo "  railway status"
echo ""
echo "  # Abrir dashboard"
echo "  railway open"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "🎉 ¡FELICITACIONES! Tu API está en producción."
echo ""
echo "¿Tienes problemas? Revisa:"
echo "  • RAILWAY_RENDER_DEPLOYMENT.md"
echo "  • QUICKSTART.md"
echo "  • Los logs en Railway dashboard"
echo ""
